version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=customfit_user
      - MYSQL_PASSWORD=your_password_here
      - MYSQL_DATABASE=customfit
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=customfit
      - MYSQL_USER=customfit_user
      - MYSQL_PASSWORD=your_password_here
      - MYSQL_ROOT_PASSWORD=root_password_here
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
